### ISSUE TITLE
Radio buttons and checkboxes are not focusable

### ISSUE THREAD

**Issue by rkojik** [Office-of-Digital-Innovation/California-State-Template-v5-Beta#16]
No need to use a hidden class to hide the input. It's better to utilize CSS more and HTML less to accomplish the custom styled radio buttons / checkboxes: 

The only HTML you need: 
`<label>
<input type="checkbox">
<span>Checkbox 1</span>
</label>`

Then you can use adjacent sibling selectors in CSS: 
[https://codepen.io/stefsullrew/pen/XJVOvK](url)

**Comment by kkoryaka** [comment]
Good catch. Thank you, The issue is now fixed.
