### ISSUE TITLE
Anchor Issue with Fixed Header

### ISSUE THREAD

**Issue by susan-k** [Office-of-Digital-Innovation/California-State-Template-v5-Beta#2]
Hi,

I noticed an issue when using anchors on a page with a fixed header.  When I click on the anchor, the top part of the text is hidden below the fixed header.  However, when I changed the header to not be "fixed", the anchor works.

I added an anchor to go to the H3 title on the "general-landing.html" sample page and after clicking on the link, the text that appears at the very bottom of the fixed header is the very last sentence under the Heading 3 paragraph:  ante nulla, gravida elementum condimentum ornare, varius eget dolor.

(see attached)  
[v5_anchor_fixed_header_issue.docx](https://github.com/Office-of-Digital-Innovation/California-State-Template-v5-Beta/files/730924/v5_anchor_fixed_header_issue.docx)

Can the template be fixed so we can use anchors with fixed headers?

Let me know if you have any questions.

Thank you,

Susan Kelly
SWRCB Web Unit

**Comment by Greg-Watanabe** [comment]
Try adding this to one of your .css files. Let me know if it causes any side effects.

    .fixed + div :target:before {
    	display: block;
    	content: "";
    	height: 110px;
    	margin: -110px 0 0;
    }

**Comment by susan-k** [comment]
Hi Greg

I added the code to several of our css files and it didn’t seem to change anything for me.

Our unaltered test site is under folder “ver5” so I added the code to the “ver5/css/cagov.core.css” file yet that didn’t work thus removed code.  I then added the code to the root “cagov.core.css” file and it still didn’t work thus removed code.

Next, I added the code to both the root and ver5 “colorscheme-oceanside.css” files and it still didn’t work.

I also changed the includes on the “ver5/ssi/head-css-js.html” file to use the css under the “ver5” folder and not the root.

Any suggestions?


Susan Kelly
SWRCB | DIT | Web Dev Unit
(916) 341-5218
Susan.Kelly@waterboards.ca.gov<mailto:Susan.Kelly@waterboards.ca.gov>

**Comment by Greg-Watanabe** [comment]
Could you put your site somewhere where I can view it, or zip it and post it here?

**Comment by susan-k** [comment]
Hi Greg

I found a solution that seems to work pretty good.  It’s at:  http://fellowtuts.com/html-css/offsetting-anchor-hash-tag-links-to-adjust-for-fixed-header/

It’s a simple addition to the custom css file and class to the anchors.

Susan

**Comment by susan-k** [comment]
Hi Greg

I just realized why your code didn't work for me.  I forgot to add the class to the anchor.  I added similar code and it works.

Thank you for your help.

Susan
