### ISSUE TITLE
Source Files

### ISSUE THREAD

**Issue by markaplet** [Office-of-Digital-Innovation/California-State-Template-v5-Beta#3]
Any plans to release the source LESS and JS files? If so when?

**Comment by willyfresh** [comment]
can I latch onto this question? will you also release package.json and grunt/gulp files?

**Comment by artuoma** [comment]
Yes we are very close to having those completed and will release soon.

**Comment by artuoma** [comment]
Please see commit 778e4c3 for latest source files.
