### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by myque08** [Office-of-Digital-Innovation/California-State-Template-v5-Beta#4]
Google is discontinuing support for CSE API 1.0. Are you going to be updating to API 2.0?

**Comment by artuoma** [comment]
Yes we have a solution and will be uploading shortly, thanks.

**Comment by artuoma** [comment]
Please see commit 778e4c3 for latest search API. You can see the latest changes at http://beta.template.webtools.ca.gov
