### ISSUE TITLE
Contrast issues

### ISSUE THREAD

**Issue by myque08** [Office-of-Digital-Innovation/California-State-Template-v5-Beta#5]
This only applies if you are trying to meet WCAG 2.0 AA standards.

The blue of the header (#046B99) and the orange highlight (#FDB81E) contrast only 3.4, which means the fonts would have to be at least size 18, but are set to 16 in the header area. So, the links stop qualifying for contrast when hovered over.

**Comment by myque08** [comment]
Another contrast issue is the color of links (#428bca) against white.  I've replaced it with #3A7AB2, which gives AA in contrast, but not AAA.

**Comment by artuoma** [comment]
Hello, thanks for that feedback, we have incorporated these fixes in commit 60a99dd .
