### ISSUE TITLE
Split the CaGov and Color Scheme

### ISSUE THREAD

**Issue by WebmasterJ** [Office-of-Digital-Innovation/California-State-Template-v5-Beta#7]
I've split the CaGov core file and the Color Scheme file, so that entities wishing to change just the color scheme can do so with ease. The color scheme can be modified further by the original publisher so the CSS files are smaller in size, by removing unnecessary CSS.

[cagov-colorscheme.zip](https://github.com/Office-of-Digital-Innovation/California-State-Template-v5-Beta/files/911553/cagov-colorscheme.zip)

**Comment by elcy-b** [comment]
So instead of overriding the core, the color scheme can be totally separate?

**Comment by artuoma** [comment]
Take a look at commit 177f315, The color scheme structure has been changed to avoid duplication of styles in cagov.core.css which now imports color scheme variables only, the rest goes into the color scheme css
